CC      = gcc
CFLAGS  = -Iinclude -Wall -Wextra -Wpedantic -std=c11
TARGET  = app
SRCS    = src/stack.c main.c

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o $(TARGET)

clean:
	rm -f $(TARGET)
